export const OUT = Object.freeze({
  authenticate: 'game:auth',
  requestSnapshot: 'game:sync:request',
  applicationAction: 'game:application:action',

  nodeAdd: 'game:node:add',
  nodeUpdate: 'game:node:update',
  nodeDelete: 'game:node:delete',

  activityJoin: 'game:activity:join',
  activitySkip: 'game:activity:skip',
  activityComplete: 'game:activity:complete',

  activityTaskUpdate: 'game:activity:task:update',
  activityTaskReschedule: 'game:activity:task:reschedule',
  activityTaskSkip: 'game:activity:task:skip',
  activityTaskComplete: 'game:activity:task:complete',

  activityMealUpdate: 'game:activity:meal:update',
  activityMealSkip: 'game:activity:meal:skip',
  activityMealComplete: 'game:activity:meal:complete',

  activityWorkoutUpdate: 'game:activity:workout:update',
  activityWorkoutSelect: 'game:activity:workout:select',
  activityWorkoutReschedule: 'game:activity:workout:reschedule',
  activityWorkoutCheckIn: 'game:activity:workout:check-in',

  tileReveal: 'game:tile:reveal',
  suggestedStopDecision: 'game:suggested-stop:decision',

  postReplyCreate: 'game:post:reply:create',
  postSave: 'game:post:save',
  hyperlinkVote: 'game:hyperlink:vote',

  // Account/social hub
  conversationsRequest: 'game:social:conversations:request',
  conversationOpen: 'game:social:conversation:open',
  supportConversationOpen: 'game:social:support:open',
  conversationMessagesRequest: 'game:social:conversation:messages:request',
  conversationMessageSend: 'game:social:conversation:message:send',
  friendsRequest: 'game:social:friends:request',
  postsRequest: 'game:social:posts:request',
  postFeedSave: 'game:social:post:save',
  postRepliesRequest: 'game:social:post:replies:request',
  postReplySend: 'game:social:post:reply:send',

  routeSelect: 'game:route:select',
  routeBuild: 'game:route:build',
  routeReroute: 'game:route:reroute',
  routeAttachNode: 'game:route:attach-node',
  routeDraftUpdate: 'game:route:draft:update',
  routePreviewUpdate: 'game:route:preview:update',
  routePreviewCommit: 'game:route:preview:commit',

  roadInteraction: 'game:road:interaction',
  searchQuery: 'game:search:query',

  workoutCatalogRequest: 'game:play:workouts:request',
  requestPlayData: 'game:play:request',
  workoutStart: 'game:play:workout:start',
  workoutPause: 'game:play:workout:pause',
  workoutResume: 'game:play:workout:resume',
  workoutEnd: 'game:play:workout:end',
  workoutComplete: 'game:play:workout:complete',
  exerciseSelect: 'game:play:exercise:select',
  exerciseStart: 'game:play:exercise:start',
  exercisePause: 'game:play:exercise:pause',
  exerciseResume: 'game:play:exercise:resume',
  exerciseComplete: 'game:play:exercise:complete',
  exerciseSkip: 'game:play:exercise:skip',
  liveMessageSend: 'game:play:message:send',
  liveReactionSend: 'game:play:reaction:send',
});

export const IN = Object.freeze({
  snapshot: 'game:sync:snapshot',
  nodeUpserted: 'game:node:upserted',
  nodeDeleted: 'game:node:deleted',
  tileRevealState: 'game:tile:reveal:state',
  routeState: 'game:route:state',
  dayPlanState: 'game:day-plan:state',
  searchResults: 'game:search:results',
  workoutCatalog: 'game:play:workouts',
  workout: 'game:play:workout',
  liveMessage: 'game:play:message',
  liveMessages: 'game:play:messages',
  liveReaction: 'game:play:reaction',

  // Account/social hub
  conversations: 'game:social:conversations',
  conversationOpened: 'game:social:conversation:opened',
  conversationMessages: 'game:social:conversation:messages',
  conversationMessage: 'game:social:conversation:message',
  friends: 'game:social:friends',
  posts: 'game:social:posts',
  postFeedSaved: 'game:social:post:saved',
  postReplies: 'game:social:post:replies',
  postReply: 'game:social:post:reply',
  serverError: 'game:error',
});
